Vektorel.Windows.KitapBankosuApp/Models/Yazar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vektorel.Windows.KitapBankosuApp.Models
{
    public class Yazar
    {
        
        public int YazarId { get; set; }
        public string YazarAd { get; set; }
        public DateTime DogumTarih { get; set; }
    }
}

Vektorel.Windows.KitapBankosuApp/Models/YazarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vektorel.Windows.KitapBankosuApp.Models
{
    public class YazarViewModel
    {
        public IEnumerable<Yazar> Yazarlar { get; set; }
        public Yazar yazar { get; set; }
    }
}

Vektorel.Windows.KitapBankosuApp/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vektorel.Windows.KitapBankosuApp.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DashBoard()
        {
            return View();

        }
    }
}

Vektorel.Windows.KitapBankosuApp/Areas/Admin/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vektorel.Windows.KitapBankosuApp.Models;

namespace Vektorel.Windows.KitapBankosuApp.Areas.Admin.Controllers
{
   
    public class YazarController : Controller
    {
        KitapContext ctx = new KitapContext();
        // GET: Admin/Yazar
        public ActionResult Index()
        {
            YazarViewModel y = new YazarViewModel();
            y.Yazarlar = ctx.Yazarlar.ToList();
            return View(y);
        }


        [HttpGet]

        public ActionResult YazarEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YazarEkle(Yazar yz)
        {
            ctx.Yazarlar.Add(yz);
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult YazarDetay(int? id)
        {

            return View(ctx.Yazarlar.Find(id));
        }

        public ActionResult YazarSil(int? id)
        {
            Yazar yz = new Yazar();
            yz=ctx.Yazarlar.Find(id);

          ctx.Yazarlar.Remove(yz);
            ctx.SaveChanges();
            return RedirectToAction("Index");
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ctx.Dispose();

            }

        }
    }
}

Vektorel.Windows.KitapBankosuApp/Areas/Admin/Views/Home/DashBoard.cshtml
@{
    ViewBag.Title = "DashBoard";
}

<h2>DashBoard</h2>

Vektorel.Windows.KitapBankosuApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>AdminLTE 3 | Starter</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
    <!-- Theme style -->
    <link href="~/Content/adminlte.min.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-comments"></i>
                        <span class="badge badge-danger navbar-badge">3</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Brad Diesel
                                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">Call me whenever you can...</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                               
                                <img src="~/images/1484835709_trinity-kutuphane.jpg" alt="User Avatar"class="img-size-50 img-circle mr-3" />  
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        John Pierce
                                        <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">I got your message bro</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Nora Silvester
                                        <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">The subject goes here</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                    </div>
                </li>
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                        <i class="fas fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/images/1484835709_trinity-kutuphane.jpg" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Kitap Bankosu</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="info">
                        <a href="#" class="d-block">Admin</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Ana Sayfa
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="#" class="nav-link active">
                                        <p>Active Page</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/Admin/Yazar/Index" class="nav-link active">
                                        <p>Yazar Yönetimi</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">Starter Page</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Starter Page</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="~/Scripts/adminlte.min.js"></script>
    @RenderSection("scripts",false)
</body>
</html>

Vektorel.Windows.KitapBankosuApp/Areas/Admin/Views/Yazar/Index.cshtml
@using Vektorel.Windows.KitapBankosuApp.Models
@model YazarViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Yazar Yönetimi</h2>
<btn class="btn btn-success" data-toggle="modal" data-target="#mdlYazarEkle">Yazar Ekle</btn>
@*<a href="/Admin/Yazar/YazarEkle" class="btn btn-success" data-toggle="modal" data-target="#mdlYazarEkle">Yazar Ekle</a>*@

<h3>Yazar Listesi</h3>
<table class="table">
    <thead>
        <tr>
            <th> Yazar Ad </th>
            <th> Yazar Doğum Tarihi</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Yazarlar)
        {
            <tr>
                <td>@item.YazarAd</td>
                <td>@item.DogumTarih</td>
                <td>
                    <a href="/Admin/Yazar/YazarDetay/@item.YazarId" class="btn btn-sm btn-info">Detaylar</a><a href="/Admin/Yazar/YazarSil/@item.YazarId" class="btn btn-sm btn-danger">Sil</a>
                </td>

            </tr>

        }



    </tbody>




</table>

<div class="modal fade" id="mdlYazarEkle" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
              
                
                    <div>
                        @Html.LabelFor(yz => yz.yazar.YazarAd)
                        @Html.TextBoxFor(yz => yz.yazar.DogumTarih)
                    </div>
                    <div>
                        @Html.LabelFor(yz => yz.yazar.YazarAd)
                        @Html.TextBoxFor(yz => yz.yazar.YazarAd, new { @type = "date" })
                    </div>
                   
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                <input type="button" name="btnKaydet" id="btnKaydet" value="Kaydet " class="btn btn-success" onclick="YazarEkle()" />
            </div>
        </div>
    </div>
</div>

@section scripts
{

    
    <script>
        function YazarEkle() {
            $.ajax({
                url: "/Admin/Yazar/YazarEkle",
                type: "POST",
                data: {
                    YazarAd: $("#yazar_DogumTarih").val(),
                    DogumTarih: $("#yazar_YazarAd").val()
                },
                    success: function () {
                    alert("Ekleme başarılı");
                }
            }
            );
}
         
    </script>
}

Vektorel.Windows.KitapBankosuApp/Areas/Admin/Views/Yazar/YazarDetay.cshtml
@using Vektorel.Windows.KitapBankosuApp.Models
@model Yazar
@{
    ViewBag.Title = "YazarDetay";
}

<h2>Yazar Detayları</h2>
Yazar Ad:@Model.YazarAd <br />
Yazar Soyad:@Model.DogumTarih

Vektorel.Windows.KitapBankosuApp/Areas/Admin/Views/Yazar/YazarEkle.cshtml
@using Vektorel.Windows.KitapBankosuApp.Models
@model Yazar
@{
    ViewBag.Title = "YazarEkle";
}

<h2>Yazar Ekleme İşlemi</h2>
<form action="/Admin/Yazar/YazarEkle" method="post">
    <div>
        <lable>Yazar Ad</lable>
        <input type="text" name="Ad" id="Ad" value=" " />
    </div>
    <div>
        <lable>Doğum Tarihi</lable>
        <input type="date" name="DogumTarih" id="DogumTarih" value=" " />
    </div>
    <div>

        <input type="submit" name="btnKaydet" id="btnKaydet" value="Kaydet " class="btn btn-success" />
    </div>
</form>

@using (Html.BeginForm("YazarEkle", "Yazar", FormMethod.Post))
{
    <div>
        @Html.LabelFor(yz => yz.YazarAd)
        @Html.TextBoxFor(yz => yz.YazarAd)
    </div>
    <div>
        @Html.LabelFor(yz => yz.DogumTarih,new{@title="Doğum Tarihi"})
        @Html.TextBoxFor(yz => yz.DogumTarih,new { @type = "date" })
    </div>
    <div>
        <input type="submit" name="btnKaydet" id="btnKaydet" value="Kaydet " class="btn btn-success" />
    </div>

}